### PR TITLE
Extract class for cleaning output

### LINKED ISSUE #43: Extract output generation to a separate class
There's currently quite a lot of code that deals with formatting the output ready for it to be included in a pull request.

This should be pulled out into a class that can be tested and updated in isolation, without having to go through the whole rigmarole of clone/rake/commit/push.

### PR DESCRIPTION
**Pull request by chrismytton**
This is a subset of https://github.com/everypolitician/rebuilder/pull/63 which just introduces a cleaned up version of the `CleanedOutput` class. Hopefully doing this as a separate change will make things a bit simpler to review in smaller steps.

Fixes #43 
Part of #62

### CODE REVIEW

**Comment by chrismytton** [comment]
Just to note, this addresses the relevant parts of this review - https://github.com/everypolitician/rebuilder/pull/63#pullrequestreview-20748669.

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
I think we can live with the implementation here, although this approach is likely to get quite unwieldy over time if we start to add more transformations. I think this is generally the sort of thing that would be best done as a chain of decorators, so that each can be turned off and on at will etc. But that can be a later refactoring — the key part for now is just to split this out.

I do think that the truncation needs to be (a) explained, and (b) tested a little better, though. At the minute the tests will pass whether you're taking the first n characters or the last n (or even a random n!) Being able to specify 'n' makes it easy to test this with a small size against a readable string, so I think it's worth tweaking that test for that (e.g. a max_body_size of 5 against "Hello, world"). 

Otherwise I think this is definitely Good Enough For Now…

**Comment by chrismytton** [comment]
> I do think that the truncation needs to be (a) explained, and (b) tested a little better, though. At the minute the tests will pass whether you're taking the first n characters or the last n (or even a random n!) Being able to specify 'n' makes it easy to test this with a small size against a readable string, so I think it's worth tweaking that test for that (e.g. a max_body_size of 5 against "Hello, world").

Ah yep. I've pushed https://github.com/everypolitician/rebuilder/pull/64/commits/9041bd70a17dac004e2a275ceb76a7665f515abc to add more details about this class to the README and https://github.com/everypolitician/rebuilder/pull/64/commits/a5c09999ff0f2eecf05b09d98ac994e0ee1630df to test that it's taking the _correct_ part of the body.

Additionally I've pushed https://github.com/everypolitician/rebuilder/pull/64/commits/02f03608e1cb436b51680bbe1010b9ba9fea0915 which adds a fix for when a redaction is `nil` or `""` (it was previously adding `REDACTED` once for every character in the input!).

Finally I've pushed https://github.com/everypolitician/rebuilder/pull/64/commits/96f202a4bb41d762b1aab191daac4bd0598b1af7 which updates `app.rb` to actually use this class.

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
The two new tests here made me wonder what would happen with `redactions: nil` or `redactions: ''` (which to me seem more likely to happen than `redactions: ['']`)

… 💣  💥

**Comment by chrismytton** [comment]
> The two new tests here made me wonder what would happen with redactions: nil or redactions: '' (which to me seem more likely to happen than redactions: [''])
> 
> … 💣 💥

Good catch! As discussed in Slack I've added a fix and a test for that and made it so that you can pass a single string to `redactions` and it will do the right thing.

**Review by tmtmtmtm — APPROVED** [review]
Woot! 👍   🚀

**Pull request merged**
